### PR TITLE
Support x86 PerformanceAPI

### PR DESCRIPTION
**Pull request by PaulDance**
Dear maintainers,

The current version of the `-sys` crate does not allow for linking against the x86 variant of the underlying PerformanceAPI. It would be useful though, as it is an officially-supported target architecture.

This PR therefore adds it by doing the following:
 * Checked that the headers did not need an update: nothing changed since the last one.
 * Update the x64 library files.
 * Add the x86 library files.
 * Add support for linking against these in the build script.
 * Check that everything compiles under both `i686-pc-windows-msvc` and `x86_64-pc-windows-msvc`.
 * Run both the example and the tests compiled for `i686-pc-windows-msvc` under an x86_64 Windows machine successfully.
 * Add partial CI support for the new x86 target. It remains to see if that works.

I am aware that GitHub Actions do not offer means to select any other architecture than x86_64, therefore meaning that this new support would not be fully tested. I included some on a best-effort basis however.

Cheers,
Paul.

### CODE REVIEW

**Comment by repi** [comment]
thanks, out of curiosity what type of application is it you need `i686-pc-windows-msvc` for? 

in general we don't support that in our crates as don't have any end users using 32-bit Windows as at least for games we've built haven't supported 32-bit for the last 13 years or so

**Comment by PaulDance** [comment]
This is for a security product. Sadly, clients often run some really old systems. Supporting them is therefore important to us.

**Comment by repi** [comment]
ah that makes sense, will take a look at the PR, doesn't seem it should be too hard to maintain support in for this crate

**Review by repi — APPROVED** [review]
verified the prebuilt binaries are identical to the ones Superluminal distribute in latest stable version. let's merge this!

**Comment by PaulDance** [comment]
Thanks!
:heart:

**Pull request merged**
